[{"error_message": "invalid load key, '<'.", "function_to_run": "tf.keras.preprocessing.sequence.skipgrams(*args, **kwargs)"}, {"error_message": "invalid load key, '<'.", "function_to_run": "tf.data.TextLineDataset(path_to_file).filter(*args)"}, {"error_message": "Cannot convert a Tensor of dtype resource to a NumPy array.", "function_to_run": "obj.adapt(*args)"}, {"error_message": "cannot pickle 'tensorflow.python.client._pywrap_tf_session.TF_Operation' object", "function_to_run": "tf.strings.lower(*args)"}, {"error_message": "Cannot convert a Tensor of dtype resource to a NumPy array.", "function_to_run": "obj.get_vocabulary()"}, {"error_message": "Cannot convert a Tensor of dtype variant to a NumPy array.", "function_to_run": "obj.batch(1024).prefetch(AUTOTUNE).map(vectorize_layer).unbatch()"}, {"error_message": "cannot pickle '_thread._local' object", "function_to_run": "tf.strings.lower(*args)"}, {"error_message": "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))", "function_to_run": "tf.keras.preprocessing.sequence.skipgrams(*args, **kwargs)"}, {"error_message": "HTTPSConnectionPool(host='129.173.67.60', port=8080): Max retries exceeded with url: /api/run_experiment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f68510e0160>: Failed to establish a new connection: [Errno 111] Connection refused'))", "function_to_run": "tf.keras.preprocessing.sequence.skipgrams(*args, **kwargs)"}, {"error_message": "HTTPSConnectionPool(host='129.173.67.60', port=8080): Max retries exceeded with url: /api/run_experiment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5d34983160>: Failed to establish a new connection: [Errno 111] Connection refused'))", "function_to_run": "tf.keras.preprocessing.sequence.skipgrams(*args, **kwargs)"}, {"error_message": "HTTPSConnectionPool(host='129.173.67.60', port=8080): Max retries exceeded with url: /api/run_experiment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fed59ea4160>: Failed to establish a new connection: [Errno 111] Connection refused'))", "function_to_run": "tf.keras.preprocessing.sequence.skipgrams(*args, **kwargs)"}, {"error_message": "HTTPSConnectionPool(host='129.173.67.60', port=8080): Max retries exceeded with url: /api/run_experiment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadb3479160>: Failed to establish a new connection: [Errno 111] Connection refused'))", "function_to_run": "tf.keras.preprocessing.sequence.skipgrams(*args, **kwargs)"}, {"error_message": "HTTPSConnectionPool(host='129.173.67.60', port=8080): Max retries exceeded with url: /api/run_experiment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5645e63160>: Failed to establish a new connection: [Errno 111] Connection refused'))", "function_to_run": "tf.keras.preprocessing.sequence.skipgrams(*args, **kwargs)"}, {"error_message": "HTTPSConnectionPool(host='129.173.67.60', port=8080): Max retries exceeded with url: /api/run_experiment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f470ed93160>: Failed to establish a new connection: [Errno 111] Connection refused'))", "function_to_run": "tf.keras.preprocessing.sequence.skipgrams(*args, **kwargs)"}, {"error_message": "HTTPSConnectionPool(host='129.173.67.60', port=8080): Max retries exceeded with url: /api/run_experiment (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9fd9c6f160>: Failed to establish a new connection: [Errno 111] Connection refused'))", "function_to_run": "tf.keras.preprocessing.sequence.skipgrams(*args, **kwargs)"}]